"""add_selected_color_and_privacy_to_workspaces

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-19 08:11:49.026688

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('workspaces', sa.Column('selected_color', sa.String(length=50), server_default=sa.text("'#2563EB'"), nullable=True))
    op.add_column('workspaces', sa.Column('privacy', sa.Enum('PUBLIC', 'PRIVATE', name='workspaceprivacy', native_enum=False, length=20), server_default=sa.text("'PRIVATE'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'privacy')
    op.drop_column('workspaces', 'selected_color')
    # ### end Alembic commands ###
